In [1]:
import pandas as pd

In [10]:
df=pd.read_csv('analysis_id(in).csv')

In [11]:
df

,Unnamed: 0,date_hour,client,device_type,time_zone,os_name,browser_name,ad_unit,size,bidder,...,sum_time_to_respond,median,min_bid,max_bid,avg_bid,sum_2nd_highest_bid,sum_prebid_winning_bid,sum_winning_bid,sum_nobid,sum_timeout
0,0,2021-04-11T01:00:00,asc126828,Desktop,America/Chicago,Linux,Chrome-85.04183133,div-gpt-ad-BT-D-Footers,728x90,onemobile,...,6614.0,NaN,0.58520,0.58520,0.585200,0.5852,0.5852,NaN,NaN,NaN
1,1,2021-04-11T01:00:00,asc126828,Desktop,America/Chicago,Linux,Chrome-85.04183133,div-gpt-ad-BT-D-Footers,728x90,rhythmone,...,5171.0,NaN,0.33945,0.34875,0.344100,NaN,NaN,NaN,NaN,NaN
2,2,2021-04-11T01:00:00,asc126828,Desktop,America/Chicago,Linux,Chrome-85.04183133,div-gpt-ad-BT-D-InLine-1,300x250,undertone,...,1523.0,NaN,0.96000,0.96000,0.960000,NaN,NaN,NaN,NaN,NaN
3,3,2021-04-11T01:00:00,asc126828,Desktop,America/Chicago,Linux,Chrome-85.04183133,div-gpt-ad-BT-D-O-300x250-1,300x250,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,2021-04-11T01:00:00,asc126828,Desktop,America/Chicago,Linux,Chrome-85.04183133,div-gpt-ad-BT-D-O-300x250-1,300x250,rhythmone,...,3570.0,0.34875,0.34410,0.34875,0.346425,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,4995,2021-04-11T01:00:00,asc126828,Desktop,America/New_York,Windows,Chrome-89.04389114,div-gpt-ad-BT-D-InPost-8_1_20,468x60,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4996,4996,2021-04-11T01:00:00,asc126828,Desktop,America/New_York,Windows,Chrome-89.04389114,div-gpt-ad-BT-D-InPost-8_1_20,728x90,medianet,...,363.0,0.05828,0.05828,0.05828,0.058280,NaN,NaN,NaN,NaN,NaN
4997,4997,2021-04-11T01:00:00,asc126828,Desktop,America/New_York,Windows,Chrome-89.04389114,div-gpt-ad-BT-D-InPost-8_1_22,468x60,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4998,4998,2021-04-11T01:00:00,asc126828,Desktop,America/New_York,Windows,Chrome-89.04389114,div-gpt-ad-BT-D-InPost-8_1_27,310x260,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4999,4999,2021-04-11T01:00:00,asc126828,Desktop,America/New_York,Windows,Chrome-89.04389114,div-gpt-ad-BT-D-InPost-8_1_33,728x90,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
# Question 1: The above data is data for prebid auctions. 
# There are bidders who receive requests for placing ads, they respond to these requests with a bid and the highest bid wins the auction.
# Analyse the dataset to answer which bidder has the highest win rate (wins / total_bid).

df.columns

Index(['Unnamed: 0', 'date_hour', 'client', 'device_type', 'time_zone',
       'os_name', 'browser_name', 'ad_unit', 'size', 'bidder', 'bid_range',
       'media_type', 'request_count', 'response_count', 'prebid_win_count',
       'win_count', 'sum_bid', 'sum_time_to_respond', 'median', 'min_bid',
       'max_bid', 'avg_bid', 'sum_2nd_highest_bid', 'sum_prebid_winning_bid',
       'sum_winning_bid', 'sum_nobid', 'sum_timeout'],
      dtype='str')

In [13]:
df['bidder'].nunique()

18

In [22]:
# prebid win count vs win count- need to look about it
# media - type- need to see
df['win_count']=df['win_count'].fillna(0)
df['prebid_win_count']=df['prebid_win_count'].fillna(0)
# win rate calculation
df['win_rate']=df['win_count']/df['response_count']
df['prebid_win_rate']=df['prebid_win_count']/df['response_count']
bidder_stats=df.groupby('bidder').agg({
    'win_count':'sum',
    'prebid_win_count':'sum',
    'response_count':'sum'
})
bidder_stats['overall_win_rate_pct']=(bidder_stats['win_count']/bidder_stats['response_count'])*100
bidder_stats['prebin_win_rate_pct']=(bidder_stats['prebid_win_count']/bidder_stats['response_count'])*100

In [23]:
bidder_stats.sort_values(by='overall_win_rate_pct',ascending=False).head()

,win_count,prebid_win_count,response_count,overall_win_rate_pct,prebin_win_rate_pct
bidder,,,,,
undertone,16.0,52.0,104,15.384615,50.000000
emx_digital,20.0,56.0,393,5.089059,14.249364
sharethrough,10.0,104.0,332,3.012048,31.325301
rhythmone,18.0,160.0,655,2.748092,24.427481
pulsepoint,5.0,71.0,191,2.617801,37.172775